# -*- coding: utf-8 -*-
"""71230976_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWfv7d0Aw6znxjqFUjzrpz2c8ngVOKO_
"""

#latman 11.1
tA = (90,90,90,90)
tB = tA[0]
for i in tA:
    if i == tB:
        tC = ("True")
    else:
        print(False)
        exit()
print(tC)

#latman 11.2
nim = input("masukkan nim :")
nama = input("masukkan nama lengkap :")
alamat = input("masukkan alamat :")
print()

print("Data")
print("NIM :", nim)
print("NAMA :", nama)
print("ALAMAT :", alamat)
print()

NIM= tuple(nim)
print("NIM :", NIM)
x = nama.split()
Nama_depan = tuple(x[0][0:])
print("NAMA DEPAN :", Nama_depan)
x = nama.split()
Nama_terbalik = x[::-1]
print("NAMA TERBALIK :", tuple(Nama_terbalik))

# #latman 11.3
namafile = input('Enter file name: ')
domain = dict()
daftar =  list()

try:
    handle = open(namafile)
except:
    print('File cannot be opened:', namafile)
    exit()

for line in handle:
    kata = line.split()
    if len(kata) < 2 or kata[0] != "From":
      continue
    post = kata[5].split(":")
    jam = post[0]
    if jam not in domain:
        domain[jam] = 1
    else:
        domain[jam] += 1
for key, val in list(domain.items()):
    daftar.append((key, val))
daftar.sort()
for key, val in daftar:
    print(key, val)
