# -*- coding: utf-8 -*-
"""71230976.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FcBb9AiYw4SRvr5o5noo6c8ogos4OPt2

1 Buatlah satu Notebook baru, berilah nama notebook tersebut dengan format Nama
lengkap (NIM) anda. Kemudian ketikkan ulang kode program seperti yang ada di Gambar 1.24.
Tuliskan langkah-langkah yang anda lakukan secara berurutan, sampai mendapatkan hasil
seperti pada gambar tersebut. Perhatikan, anda harus menjelaskan langkah-langkah disertai
gambar/screenshot. Jangan lupa memasukkan langkah-langkah instalasi package-package yang
diperlukan (matplotlib dan numpy). Instalasi package tersebut biasanya tidak diperlukan jika
anda menginstall Python dari Anaconda.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0,10)
y = np.sin(x)
z = np.cos(x)

plt.plot(x,y,'b',x,z,'r')
plt.xlabel('Radians');
plt.ylabel('Value');
plt.title('Plotting Demostration')
plt.legend(['sin','cos'])
plt.grid()

"""Latihan 1.2 Gerard membeli emas 25 gram dengan harga Rp. 650.000/gram. Jika sekarang
harga emas menjadi Rp. 685.000/gram,
• Berapa keuntungan yang didapat oleh Gerard (dalam Rp dan dalam %)?
• Jika Gerard kemudian membeli lagi 15 gram emas dengan harga Rp. 685.000, maka
Gerard sekarang memiliki total 40 gram emas. Jika kemudian harga emas naik lagi
menjadi Rp. 715.000, berapa keuntungan yang didapat oleh Gerard (dalam Rp dan dalam
%)?
Gunakan Python mode interaktif untuk menyelesaikan permasalahan tersebut. Tampilkan
dan jelaskan secara lengkap langkah-langkah yang anda lakukan, dimulai dari membuka Python
mode interaktif di komputer anda masing-masing
"""

# Gerard membeli emas 25 gram dengan harga Rp. 650.000/gram
# Harga emas menjadi Rp. 685.000/gram

emasgerald1 = 25
hargabeli_1 = 650000
hargajual_1 = 685000

# keuntungan => harga jual - harga beli
keuntungan1 = int(emasgerald1*hargajual_1 - emasgerald1*hargabeli_1)
untung1 = float((keuntungan1*100)/(emasgerald1*hargabeli_1))
print (f"Emas gerald = {emasgerald1}gram")
print (f"Keuntungan pertama = {keuntungan1}")
print (f"Persentase Keuntungan pertama = {untung1}%")

beliemas = 15
emasgerald2 = emasgerald1 + beliemas
hargabeli_2 = 685000
hargajual_2 = 715000

keuntungan2 = int((emasgerald2*hargajual_2)-(emasgerald1*hargabeli_1)-(beliemas*hargabeli_2))
untung2 = float((keuntungan2*100)/((emasgerald1*hargabeli_1)+(beliemas*hargabeli_2)))
print (f"Emas gerald = {emasgerald2}gram")
print (f"Keuntungan kedua= {keuntungan2}")
print (f"Persentase Keuntungan kedua = {untung2}%")

"""Latihan 1.3 Berkaitan dengan compound interest pada Contoh 1.2 dan 1.3, jika Erika memiliki
uang 200 juta rupiah dan ingin disimpan di deposito Pasti Cuan sampai uangnya menjadi
minimal 400 juta, berapa lama waktu yang dibutuhkan?
catatan: bunga 10% per-tahun.
Gunakan Python mode interaktif untuk menyelesaikan permasalahan tersebut. Tampilkan
dan jelaskan secara lengkap langkah-langkah yang anda lakukan, dimulai dari membuka Python
mode interaktif di komputer anda masing-masing.
"""

# Uang Awal Erika Rp. 200.000.000,00
# Bunga Deposito 10%/Tahun

uangerika = 200000000
bunga = 10
a = uangerika
thun = 0
while a <= 400000000:
  thun=thun+1
  a = float(a*((100+bunga)/100))

b = float(round(a))
print (f"Perlu waktu {thun} tahun untuk merubah Rp. 200000000 menjadi Rp {b}")