# -*- coding: utf-8 -*-
"""71230976_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tE-xS6raeo-AS7SkuD0I7P6R-DjKstFx
"""

#Latihan 14.1
import re
from datetime import datetime

sekarang = datetime.now()

tahun = sekarang.year
bulan = sekarang.month
hari = sekarang.day
b = (f'{hari}-{bulan}-{tahun}')
grup = re.compile(r'\d{4}-\d{2}-\d{2}')
txt = open("n.txt", "r")
txt2 = txt.read()
a = []
findd = grup.findall(txt2)

for x in findd:
    v = x.split('-')
    c = (v[2]+"-"+v[1]+"-"+v[0])
    a.append(c)
date_format = "%d-%m-%Y"
b = datetime.strptime(b, date_format)
for y in a:
    c = datetime.strptime(y, date_format)
    d = b - c
    print(f'{y} 00:00:00 selisih {d.days} hari')

#latman 14.2
import re
import random
import string


with open('x.txt', 'r') as file:
    teks = file.read()


email_regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
email_list = re.findall(email_regex, teks)


for email in email_list:
    username = email.split('@')[0]
    password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
    print(f"{email} username: {username} , password: {password}")