# -*- coding: utf-8 -*-
"""71230976_13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jX0YwzK8-o_5K5ccrukMYN4qd4EDQDIw
"""

#Latihan 13.1
def cekprima(a, b = None):
    if a <= 1:
        print("Bukan bilangan prima")
        return False
    if b is None:
        b = a - 1
    if b < 2:
        print("Ini bilangan prima")
        return True
    if a % b == 0:
        print("Bukan bilangan prima")
        return False
    return cekprima(a, b - 1)

a = int(input("Masukkan angka: "))
cekprima(a)

#Latihan 13.2
def hanya_huruf(s):
    return ''.join(char.lower() for char in s if char.isalpha())

def palindrom(s):
    if len(s) < 1:
        return True
    else:
        if s[0] == s[-1]:
            return palindrom(s[1:-1])
        else:
            return False

s = input("Masukkan kata: ")
s = hanya_huruf(s)
if palindrom(s):
    print("Palindrom")
else:
    print("Bukan Palindrom")

#Latihan 13.3
n1 = 1
n2 = int(input("Masukkan limit bilangan (n): "))

def jumlah_ganjil(n1, n2):
    if n1 > n2:
        return 0
    return n1 + jumlah_ganjil(n1 + 2, n2)

print("Jumlah bilangan ganjil dalam rentang:", jumlah_ganjil(n1, n2))

#Latihan 13.4
def jumlahangka(n):
    if len(n) == 0:
        return 0
    else:
        o = int(n[-1])
        n = n[:-1]
        return o + jumlahangka(n)

n = input("Masukkan angka: ")
print(jumlahangka(n))

#Latihan 13.5

def kombinasi(r, n):
    if n == 0:
        return 1
    else:
        int((r-n+1)/ n)
        return (kombinasi(r,n-1) * (r-n+1) / (n))

r = int((input("Masukkan r :")))
n = int((input("Masukkan n :")))

print(kombinasi(r, n))
