# -*- coding: utf-8 -*-
"""71230976 (7).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEG-zdu3qay2JKmyUVMGHbJQx1wHlYIv
"""

#Latihan Mandiri 7.1
def anagram(h1, h2):
    h1 = h1.lower()  # Mengubah semua huruf dalam h1 menjadi huruf kecil
    h2 = h2.lower()  # Mengubah semua huruf dalam h2 menjadi huruf kecil
    if sorted(h1) == sorted(h2):
        print("anagram")
    else:
        print("Tidak anagram")

h1 = str(input("Masukkan kata 1: "))
h2 = str(input("Masukkan kata 2: "))

anagram(h1, h2)

#Latihan Mandiri 7.2
def hitung_frekuensi(kalimat, kata) :
    kalimat = kalimat.lower()
    kata = kata.lower()
    hasil = kalimat.count(kata)
    print(f'{kata} ada {hasil} buah.')

kalimat = input("masukkan kalimat : ")
kata = input("masukkan kata : ")

hitung_frekuensi(kalimat, kata)

#Latihan Mandiri 7.3
def hapus_spasi(kalimat):
    kalimat_tanpa_spasi = " ".join(kalimat.split())
    return kalimat_tanpa_spasi

kalimat_input = input("Masukkan kalimat dengan spasi yang ingin dihapus: ")
print(hapus_spasi(kalimat_input))

#Latihan Mandiri 7.4
def cek_kata(kalimat):
    kata = kalimat.split()
    terpendek = min(kata, key=len)
    terpanjang = max(kata, key=len)
    print("Kata terpendek:", terpendek)
    print("Kata terpanjang:", terpanjang)

kalimat = input("Masukkan kalimat: ")
cek_kata(kalimat)

