# -*- coding: utf-8 -*-
"""71230976(tugas 5).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgzx1YuaW-GkQxvmpUDxjIP4_mnIWk3j
"""

#Latihan Mandiri 5.1

def perkalian(bil1, bil2):
    hasil = 0
    print(f"{bil2} x {bil1} = ", end="")
    for i in range(bil2):
        hasil += bil1
        if i < bil2 - 1:
            print(f"{bil1} + ", end="")
        else:
            print(f"{bil1} = ", end="")
    return hasil

bil1 = int(input("Masukkan bilangan yang dikali : "))
bil2 = int(input("Masukkan bilangan perkalian : "))
print(perkalian(bil1, bil2))

#Latihan Mandiri 5.2

def ganjil(bil1, bil2):
    if bil2 > bil1 :
        while bil2 != bil1 :
            if bil2 % 2 == 1 :
                print(bil2, end=",")
            bil2 = bil2 - 1
    else :
        while bil2 != bil1 :
            bil2 = bil2 + 1
            if bil2 % 2 == 1 :
                print(bil2, end=",")

bawah = int(input("Masukkan nilai bawah : "))
atas = int(input("Masukkan nilai atas : "))
ganjil(atas, bawah)

#Latihan Mandiri 5.3

def ips(jumlah_matkul):
    total_sks = 0
    total_bobot = 0

    for i in range(jumlah_matkul):
        nilai = input(f"Nilai MK{i + 1}: ")

        if nilai == 'A':
            bobot = 4
        elif nilai == 'B':
            bobot = 3
        elif nilai == 'C':
            bobot = 2
        elif nilai == 'D':
            bobot = 1

        total_sks += 3
        total_bobot += bobot * 3

    ips = total_bobot / total_sks
    return ips

jumlah_matkul = int(input("Masukkan jumlah mata kuliah: "))
hasil = ips(jumlah_matkul)

print("Nilai IPS anda semester ini %0.2f"% hasil)
